taptapboom:
  build: .
  environment:
    - COVERALLS_REPO_TOKEN
  env_file:
    - bin/test.env
  links:
    - redis
  working_dir: /usr/src/app
  command: bash -c "npm test && npm run coverage-coveralls"
redis:
  image: redis:3.2
