
app:
  name: APP_NAME
  baseUri: APP_BASE_URI

server:
  port: PORT

postgres:
  databaseUri: POSTGRES_DATABASE_URI

spotify:
  clientId: SPOTIFY_CLIENT_ID
  clientSecret: SPOTIFY_CLIENT_SECRET
  redirectUri: SPOTIFY_REDIRECT_URI
  playlistUser: SPOTIFY_PLAYLIST_USER
  targetPlaylist: SPOTIFY_TARGET_PLAYLIST

slack:
  verificationToken: SLACK_VERIFICATION_TOKEN
  clientId: SLACK_CLIENT_ID
  clientSecret: SLACK_CLIENT_SECRET
  oAuthState: SLACK_OAUTH_STATE
